### ISSUE TITLE
Scrap Cannot Be Run Because Flash Player is Blocked

### ISSUE THREAD

**Issue by R4356th** [towerofnix/small-scrap#1]
I tried to run Scrap on my browser(Chrome) but failed. It returned a message saying Flash Player was blocked.

**Comment by towerofnix** [comment]
sorry to hear that :'o but there isnt a heck of a lot that can be done about that! chrome doesnt support flash anymore, so. youll need to look into running flash some other way - the flash debug player or installing it on firefox have both worked for me in the past.

**Comment by R4356th** [comment]
I see. Thank you.
